environments:
  prod:
    process:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_workflow
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: process
      DBT_TGT_TABLE_NAME: workflow_process
    variable:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_workflow
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: variable
      DBT_TGT_TABLE_NAME: workflow_variable
    user_operation:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_workflow
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: user_operation
      DBT_TGT_TABLE_NAME: workflow_user_operation
    task:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_workflow
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: task
      DBT_TGT_TABLE_NAME: workflow_task
    job:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_workflow
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: job
      DBT_TGT_TABLE_NAME: workflow_job
    form_property:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_workflow
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: form_property
      DBT_TGT_TABLE_NAME: workflow_form_property

    appointment:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: appointment
      DBT_TGT_TABLE_NAME: appointment_appointment
    availability_slots:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: availability_slots
      DBT_TGT_TABLE_NAME: appointment_availability_slots
    consultation:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: consultation
      DBT_TGT_TABLE_NAME: appointment_consultation
    consultation_notes:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: consultation_notes
      DBT_TGT_TABLE_NAME: appointment_consultation_notes
    patient:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: patient
      DBT_TGT_TABLE_NAME: appointment_patient
    stg_appointment_slots:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: stg_appointment_slots
      DBT_TGT_TABLE_NAME: appointment_stg_appointment_slots
    mo_report:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: event
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: coreruby_transactions_native
      DBT_TGT_TABLE_NAME: reconciliation_mo_report
    m1_report:
      DBT_SRC_GCP_PROJECT: my-prod-project
      DBT_SRC_GCP_DATASET: event
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: coreruby_transactions_native
      DBT_TGT_TABLE_NAME: reconciliation_m1_report
  preprod:
    mo_report:
      DBT_SRC_GCP_PROJECT: my-proprod-project
      DBT_SRC_GCP_DATASET: event
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: coreruby_transactions_native
      DBT_TGT_TABLE_NAME: reconciliation_mo_report
    m1_report:
      DBT_SRC_GCP_PROJECT: my-proprod-project
      DBT_SRC_GCP_DATASET: event
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: coreruby_transactions_native
      DBT_TGT_TABLE_NAME: reconciliation_m1_report
    consultation:
      DBT_SRC_GCP_PROJECT: my-proprod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: consultation
      DBT_TGT_TABLE_NAME: appointment_consultation
    consultation_notes:
      DBT_SRC_GCP_PROJECT: my-proprod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: consultation_notes
      DBT_TGT_TABLE_NAME: appointment_consultation_notes
    patient:
      DBT_SRC_GCP_PROJECT: my-proprod-project
      DBT_SRC_GCP_DATASET: my_domain_appointment
      DBT_GCP_DATASET: my_operational
      DBT_SRC_TABLE_NAME: patient
      DBT_TGT_TABLE_NAME: appointment_patient